" .vimrc
set nocompatible

" set runtime location for pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim

" start pathogen
call pathogen#infect()

if has('autocmd')
  filetype on
  filetype indent on
  filetype plugin on
endif

let g:solarized_termtrans=1
let g:solarized_termcolors=256

if has('gui_running')
  set background:light
endif

if has('syntax')
  syntax enable
  set background=light
  colorscheme solarized
endif

if has('cmdline_info')
  set ruler
  set showcmd
  set showmode
endif

if has('statusline')
  set laststatus=2
  set statusline=%<%f\
  set statusline+=%w%h%m%r
  set statusline+=\ [%{getcwd()}]
  set statusline+=%=%-14.(%l.%c%V%)\ %p%%
endif

set shiftwidth=2
set softtabstop=2
set expandtab
set number
set cursorline
set nofoldenable
let g:vim_markdown_folding_disabled=1
