#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Robb Schiller - http://robbschiller.com/

Additional software to install

Browsers:
    Firefox
    FirefoxNightly
    Google Chrome
    Google Chrome Canary
    Opera

Development:
    Xcode
    Sublime Text 3
    iTerm 2
    ImageOptim
    Anvil
    Mou

Design:
    LayerVault
    Adobe CC
    Sketch
    Slicy
    Skala Preview
    LiveView

Other:
    Alfred
    Moom
    CloudApp
    Dropbox
    Flux
    LimeChat
    Skype
EOT

}
