#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Robb Schiller - http://robbschiller.com/

Additional software to install

Browsers:
    Firefox
    FirefoxNightly
    Google Chrome
    Google Chrome Canary
    Opera

Development:
    Xcode

Design:
    Sketch

Other:
    Moom
    CloudApp
    Dropbox
    LimeChat

EOT

}
