#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Robb Schiller - http://robbschiller.com/

Additional software to install

Development:
    Xcode

Design:
    Sketch
    Figma
    Framer
    Abstract

Other:
    Dropbox
    ShiftIt
    Kap
    Slack
    Alfred

EOT

}
