export EDITOR=/usr/bin/vim
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kennethreitz"

# aliases
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
alias sudo="sudo "
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"
alias g="git"
alias gs="git status"
alias ga="git add ."
alias gc="git commit -m"
alias nvm="nvm"

# Updates
export UPDATE_ZSH_DAYS=13

plugins=(git bower brew sublime python virtualenv virtualenvwrapper)

source $ZSH/oh-my-zsh.sh
