export EDITOR=/usr/bin/vim
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kennethreitz"

alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

alias gs="git status"
alias nvm="nvm"

plugins=(git tmux npm bower brew sublime python virtualenv virtualenvwrapper)

source $ZSH/oh-my-zsh.sh
